### PR TITLE
Describe namespaces and changing tags

### PR DESCRIPTION
**Pull request by mnm678**
This adds a section about namespaces and how to manage tags that change as images are moved across registries.

### CODE REVIEW

**Comment by SteveLasker** [comment]
Tag, namespace, registry are all loose terms. We've tried to accommodate a common naming to facilitate a consistent conversation without having to address, "what do you mean by `:tag`".
Please see here: https://github.com/notaryproject/requirements/blob/main/definitions-terms.md

When an artifact moves, the only real assurance you can get is the digest. We're discussing using artifact `repo:tag` as an additional element. 

The key issue captured in the Notary v2 requirement is content copy between registries must be able to copy the signature information to assure we don't lose the identity. https://github.com/notaryproject/requirements#goals

**Comment by mnm678** [comment]
> Tag, namespace, registry are all loose terms. We've tried to accommodate a common naming to facilitate a consistent conversation without having to address, "what do you mean by `:tag`".
> Please see here: https://github.com/notaryproject/requirements/blob/main/definitions-terms.md

Thanks for the link, I updated the pr accordingly.

> 
> When an artifact moves, the only real assurance you can get is the digest. We're discussing using artifact `repo:tag` as an additional element.
> 
> The key issue captured in the Notary v2 requirement is content copy between registries must be able to copy the signature information to assure we don't lose the identity. https://github.com/notaryproject/requirements#goals

This is exactly what I'm hoping to address in this new section. If the artifact, including the `repo:tag`, is signed in one registry or repository, how can that be verified in another registry or repository.

**Comment by sudo-bmitch** [comment]
From the [discussion on moving artifacts](https://github.com/notaryproject/nv2/discussions/31#discussioncomment-313127) I see this as entirely a client side process that provides some mapping between an artifact and an upstream name. I wouldn't count on any part, including `:tag` remaining the same in these artifact copies. E.g. some organization might perform a copy from `docker.io/library/alpine:3` to `internal-registry:5000/trusted/base:alpine-3` after the image goes through some verification and scanning process.

Since that's all client side, I'm not worried about defining that specific implementation as long as it's possible to create. We can always bike shed the specific design on that later.

The bigger challenges I see with moving names, since we're copying artifacts, is dealing with stale snapshots from a disconnected environment. The two options I can think of are:

1. Client side configuration to allow stale snapshots up to some threshold.
2. Running another snapshot generating tool on the artifact copy, which would likely have a different key and need a client configuration to trust the additional key used to sign these snapshots.

**Comment by mnm678** [comment]
I could see either option. The air-gapped environment could set threshold for stale timestamp/snapshot metadata (or do a slightly fancier newer-than previous metadata check as proposed [here](https://github.com/notaryproject/nv2/blob/prototype-tuf/tuf-design.md#timestamp-verification-for-air-gapped-environments)), which provides rollback protection, but with a larger attack window. If they have more resources, they could achieve slightly better protection by setting up an internal 'registry' with its own root and snapshot metadata, and configuring the client to use this internal metadata.

**Review by SteveLasker — APPROVED** [review]
For the sake of the TUF docs getting merged, I'm LGTM

**Pull request merged**
