### PR TITLE
Clean up tuf-prototype branch

### PR DESCRIPTION
**Pull request by mnm678**
This removes files related to prototype 1 from the tuf-prototype branch

### CODE REVIEW

**Comment by SteveLasker** [comment]
I believe this can be done by re-basing, as opposed to deleting.

**Comment by mnm678** [comment]
> I believe this can be done by re-basing, as opposed to deleting.

Agreed, that's a bit cleaner. I rebased in this pr, but I don't know if that'll update the history for the branch.

**Comment by SteveLasker** [comment]
If you look at the resultant state of the PR: https://github.com/notaryproject/nv2/tree/a9824cf0aec79859a3269f9ffd43ac8511a48dee it looks clean, so that's goodness.

I would suggest updating the root readme to reflect a summary as we've done in https://github.com/notaryproject/nv2/blob/prototype-1/README.md

If you can articulate the content flow between registries, as [pictured here](
https://user-images.githubusercontent.com/7647382/105899236-42e36580-5fcf-11eb-8c25-33de57ba3674.png), it would be helpful to understand how TUF would work. The ability to move signatures with the content is key.

**Comment by mnm678** [comment]
> I would suggest updating the root readme to reflect a summary as we've done in https://github.com/notaryproject/nv2/blob/prototype-1/README.md
> 
> If you can articulate the content flow between registries, as [pictured here](https://user-images.githubusercontent.com/7647382/105899236-42e36580-5fcf-11eb-8c25-33de57ba3674.png), it would be helpful to understand how TUF would work. The ability to move signatures with the content is key.

I wrote a quick description of the content flow in #34.

**Comment by mnm678** [comment]
This didn't remove the extra files. It looks like I have to force push my local branch directly to the GitHub branch

**Pull request merged**
