### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by marcofranssen**
This PR adds a very basic pipeline that compiles the binary using Go 1.14 and Go 1.15.

See: https://github.com/marcofranssen/nv2/actions/runs/483399550

Also included weekly automated checks for dependencies and Github actions updates.

### CODE REVIEW

**Comment by SteveLasker** [comment]
@marcofranssen, is this still current? 
@shizhMSFT, @aviral26, can you provide some :eyes:

**Comment by shizhMSFT** [comment]
@SteveLasker  No, it is for `prototype-1`.

Once we merge `prototype-2`, we move to `make` from `go build` since we now have multiple targets / binaries.

**Comment by marcofranssen** [comment]
I think we could merge this PR and update the build pipeline once prototype-2 arrives with more CI and replace `go-build` with `make`.

I can rebase the PR once more before we merge.

**Comment by marcofranssen** [comment]
Also opened a new PR for the prototype-2 branch. #49

**Pull request closed without merging**
